server:
  port: 81

feign:
  hystrix:
    enabled: false
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  ##activemq连接信息
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
##队列
messages:
   queue: messages_queue
